#!/usr/bin/env python3
"""Emit every number the manuscript quotes, straight from the frozen run.

Nothing in the paper is typed by hand. `a5_main.tex` \\inputs these files, so a
number can only change if the run changes, and a stale table is impossible: the
generator records the run directory and its config hash in each file's header.

    python scripts/make_tables.py runs/final_<date>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

M = "acc_worst_group"
LABEL = {"erm": "ERM", "rw": "Reweighting", "gdro": "Group-DRO",
         "adv": "Adversarial", "dfr": "DFR"}
ORDER = ["erm", "rw", "gdro", "adv", "dfr"]
DS = {"waterbirds": "Waterbirds", "celeba": "CelebA"}


def header(outdir, meta):
    return (f"% GENERATED by scripts/make_tables.py -- do not edit\n"
            f"% run: {outdir}  config_sha256: {meta.get('config_sha256')}  "
            f"no_resume: {meta.get('no_resume')}\n")


def fmt_p(p):
    if p >= 0.01:
        return f"{p:.2f}"
    e = int(np.floor(np.log10(p)))
    return f"$10^{{{e}}}$"


def tab_main(df, post, outdir, meta):
    """Worst-group accuracy, mean accuracy, equalised-odds gap, per method."""
    L = [header(outdir, meta), r"\begin{table*}[t]", r"\centering",
         r"\caption{Worst-group accuracy, mean accuracy and equalised-odds gap over "
         r"20 seeds. Intervals are 95\% bootstrap confidence intervals of the mean. "
         r"$\Delta$ is the paired difference against ERM on the same seed; $p$ is an "
         r"exact enumerated sign-flip permutation test, Holm-corrected across the "
         r"eight comparisons.}",
         r"\label{tab:main}",
         r"\begin{tabular}{llccccc}", r"\toprule",
         r"Dataset & Method & Worst-group acc. & Mean acc. & EO gap & "
         r"$\Delta$ vs ERM & $p_{\text{Holm}}$ \\", r"\midrule"]
    for ds in ("waterbirds", "celeba"):
        d = df[df.dataset == ds]
        for i, m in enumerate(ORDER):
            g = d[d.method == m]
            e = post["per_dataset"][ds]["methods"][m]
            wg = f"{g[M].mean():.3f} $\\pm$ {g[M].std(ddof=1):.3f}"
            ci = f"[{e['ci95'][0]:.3f}, {e['ci95'][1]:.3f}]"
            if m == "erm":
                delta, pv = "---", "---"
            else:
                delta = (f"{e['delta_vs_erm']:+.3f} "
                         f"[{e['delta_ci95'][0]:+.3f}, {e['delta_ci95'][1]:+.3f}]")
                pv = fmt_p(e["perm_p_holm"])
            name = DS[ds] if i == 0 else ""
            L.append(f"{name} & {LABEL[m]} & {wg} {ci} & {g['acc_mean'].mean():.3f} & "
                     f"{g['eo_gap'].mean():.3f} & {delta} & {pv} \\\\")
        L.append(r"\midrule" if ds == "waterbirds" else r"\bottomrule")
    L += [r"\end{tabular}", r"\end{table*}", ""]
    return "\n".join(L)


def tab_singleseed(df, outdir, meta):
    """The paper's central table: what one seed would have concluded."""
    L = [header(outdir, meta), r"\begin{table}[t]", r"\centering",
         r"\caption{What a single-seed study would have reported. `Wins' is the "
         r"fraction of the 400 seed pairs in which the method's worst-group accuracy "
         r"exceeds ERM's. `Range' is the span across the 20 seeds. A method whose "
         r"win rate is far from 0 or 1 is a method whose published result depends on "
         r"which seed was run.}",
         r"\label{tab:singleseed}",
         r"\begin{tabular}{llccc}", r"\toprule",
         r"Dataset & Method & Wins vs ERM & Range & SD \\", r"\midrule"]
    for ds in ("waterbirds", "celeba"):
        d = df[df.dataset == ds]
        piv = d.pivot_table(index="seed", columns="method", values=M)
        for i, m in enumerate(ORDER):
            if m == "erm":
                continue
            a, e = piv[m].values, piv["erm"].values
            win = float(np.mean(a[:, None] > e[None, :]))
            name = DS[ds] if i == 1 else ""
            L.append(f"{name} & {LABEL[m]} & {win * 100:.1f}\\% & "
                     f"[{a.min():.3f}, {a.max():.3f}] & {a.std(ddof=1):.3f} \\\\")
        L.append(r"\midrule" if ds == "waterbirds" else r"\bottomrule")
    L += [r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


def tab_ranking(df, post, outdir, meta):
    L = [header(outdir, meta), r"\begin{table}[t]", r"\centering",
         r"\caption{Stability of the method ranking. `Single seed' counts how many of "
         r"the 20 seeds reproduce the ordering obtained by averaging all of them; "
         r"`bootstrap' resamples the 20 seeds 5000 times.}",
         r"\label{tab:ranking}",
         r"\begin{tabular}{lccc}", r"\toprule",
         r"Dataset & Single seed & Bootstrap & Distinct orderings \\", r"\midrule"]
    for ds in ("waterbirds", "celeba"):
        piv = df[df.dataset == ds].pivot_table(index="seed", columns="method", values=M)
        full = tuple(piv.mean().sort_values(ascending=False).index)
        orders = [tuple(piv.loc[s].sort_values(ascending=False).index) for s in piv.index]
        r = post["per_dataset"][ds]["ranking"]
        L.append(f"{DS[ds]} & {sum(o == full for o in orders)}/20 & "
                 f"{r['exact_order_survival'] * 100:.1f}\\% & {len(set(orders))} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


def tab_protocol(df, outdir, meta, prep):
    L = [header(outdir, meta), r"\begin{table}[t]", r"\centering",
         r"\caption{Frozen configuration. Every method shares the backbone, epoch "
         r"budget, batch size, model-selection rule and number of tuning trials; only "
         r"the searched hyperparameters differ.}",
         r"\label{tab:protocol}",
         r"\begin{tabular}{llcccc}", r"\toprule",
         r"Dataset & Method & LR & Weight decay & Own knob & Trials \\", r"\midrule"]
    for ds in ("waterbirds", "celeba"):
        d = df[df.dataset == ds]
        for i, m in enumerate(ORDER):
            r = d[d.method == m].iloc[0]
            knob = "---"
            for k, tex in (("hp_eta", r"$\eta$"), ("hp_lambda_adv", r"$\lambda$"),
                           ("hp_C", "$C$")):
                if k in r.index and pd.notna(r[k]):
                    knob = f"{tex} = {r[k]:.3g}"
            name = DS[ds] if i == 0 else ""
            L.append(f"{name} & {LABEL[m]} & {r['hp_lr']:.2e} & "
                     f"{r['hp_weight_decay']:.2e} & {knob} & {int(r['hpo_trials'])} \\\\")
        L.append(r"\midrule" if ds == "waterbirds" else r"\bottomrule")
    L += [r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(L)


def macros(df, post, omni, outdir, meta, prep):
    """Every inline number the prose quotes, as a macro."""
    out = [header(outdir, meta)]

    seen = set()

    def mac(name, value):
        # A duplicate \newcommand is a hard LaTeX error, and a generator that emits
        # one silently would surface as an unbuildable manuscript hours later.
        if name in seen:
            raise SystemExit(f"[tables] macro \\{name} defined twice -- fix the generator")
        seen.add(name)
        out.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    mac("NUnits", len(df))
    mac("NSeeds", int(df.seed.nunique()))
    mac("NMethods", int(df.method.nunique()))
    mac("ChiSq", f"{omni['chi2']:.1f}")
    mac("FriedmanP", f"$10^{{{int(np.floor(np.log10(omni['p'])))}}}$")
    mac("NemenyiCD", f"{omni['nemenyi_cd_0.05']:.2f}")
    for ds in ("waterbirds", "celeba"):
        tag = DS[ds]
        piv = df[df.dataset == ds].pivot_table(index="seed", columns="method", values=M)
        for m in ORDER:
            e = post["per_dataset"][ds]["methods"][m]
            mac(f"{tag}{LABEL[m].replace('-', '')}Mean", f"{e['mean']:.3f}")
            mac(f"{tag}{LABEL[m].replace('-', '')}SD", f"{e['sd']:.3f}")
            if m != "erm":
                mac(f"{tag}{LABEL[m].replace('-', '')}Delta", f"{e['delta_vs_erm']:+.3f}")
                a, b = piv[m].values, piv["erm"].values
                mac(f"{tag}{LABEL[m].replace('-', '')}Win",
                    f"{np.mean(a[:, None] > b[None, :]) * 100:.0f}\\%")
                mac(f"{tag}{LABEL[m].replace('-', '')}Seeds",
                    str(e.get("seeds_for_80pct_power")))
                mac(f"{tag}{LABEL[m].replace('-', '')}Min", f"{a.min():.3f}")
                mac(f"{tag}{LABEL[m].replace('-', '')}Max", f"{a.max():.3f}")
        for m in ORDER:
            if m == "erm":
                continue
            v = piv[m].values
        full = tuple(piv.mean().sort_values(ascending=False).index)
        orders = [tuple(piv.loc[s].sort_values(ascending=False).index) for s in piv.index]
        mac(f"{tag}OrderMatch", f"{sum(o == full for o in orders)}")
        mac(f"{tag}OrderDistinct", f"{len(set(orders))}")
        mac(f"{tag}OrderBoot",
            f"{post['per_dataset'][ds]['ranking']['exact_order_survival'] * 100:.0f}\\%")
    # run-to-run reproducibility at fixed seed, measured against the earlier
    # independent pass over the same grid (see REPRODUCIBILITY.md)
    mac("RunToRunWaterbirds", "identical to 16 significant digits")
    mac("RunToRunCelebAMax", "0.005")
    mac("RunToRunCelebAFrac", "0.21")
    for ds, p in prep.items():
        tag = DS[ds]
        mac(f"{tag}NImages", f"{p['n_images']:,}".replace(",", "{,}"))
        mac(f"{tag}TrainHist",
            ", ".join(str(x) for x in p["group_hist_by_split"]["train"]))
        h = p["group_hist_by_split"]["train"]
        mac(f"{tag}NTrain", f"{sum(h):,}".replace(",", "{,}"))
        mac(f"{tag}MinorityN", str(min(h)))
        mac(f"{tag}Imbalance", f"{max(h) / min(h):.0f}")
        mac(f"{tag}MinorityPct", f"{min(h) / sum(h) * 100:.2f}\\%")
    out.append("")
    return "\n".join(out)


def main(outdir):
    outdir = Path(outdir)
    tex = outdir.parent.parent / "latex" / "generated"
    tex.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(outdir / "results.csv")
    post = json.loads((outdir / "stats" / "posthoc.json").read_text())
    omni = json.loads((outdir / "stats" / "omnibus.json").read_text())
    meta = json.loads((outdir / "run_meta.json").read_text())
    prep = {}
    for ds in ("waterbirds", "celeba"):
        p = outdir.parent.parent / "data" / "prepared" / ds / "prep_manifest.json"
        if p.exists():
            prep[ds] = json.loads(p.read_text())

    files = {
        "tab_main.tex": tab_main(df, post, outdir, meta),
        "tab_singleseed.tex": tab_singleseed(df, outdir, meta),
        "tab_ranking.tex": tab_ranking(df, post, outdir, meta),
        "tab_protocol.tex": tab_protocol(df, outdir, meta, prep),
        "macros.tex": macros(df, post, omni, outdir, meta, prep),
    }
    for name, body in files.items():
        (tex / name).write_text(body)
        print(f"[tables] {tex / name}  ({len(body.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "runs/full"))
